FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=nonintercative

# RUN apt-get update 

RUN apt-get update && \
    apt-get install -y wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# && apt-get install -y software-properties-common gcc && \
#     add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y python3-distutils python3-pip python3-apt git

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
     /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

WORKDIR /code

COPY "./vall-e" .


# RUN conda create -n vall  python=3.10.8 

COPY environment.yml .
RUN conda env create -f environment.yml

SHELL ["conda", "run", "-n", "vall", "/bin/bash", "-c"]

# RUN echo "Make sure torch is installed:"
RUN pip3 install .
    
COPY test.py .

# ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "vall"]
# CMD ["python", "-m", "vall_e.emb.g2p", "data/test"]